package Vistas;

import Listas.Factura;
import static Vistas.NuevoProducto.TxtProductos;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import proyectoestructuras.Utils;
import static proyectoestructuras.Utils.nuevoProducto;
import static proyectoestructuras.Utils.Login;
import static proyectoestructuras.Utils.NumeroFacDisponible;
import static proyectoestructuras.Utils.cola;
import static proyectoestructuras.Utils.listaFacturasActivas;
import static proyectoestructuras.Utils.listaFacturasNulas;
import static proyectoestructuras.Utils.pila;
import static proyectoestructuras.Utils.nuevaFactura;
import static proyectoestructuras.Utils.usuarioActual;

/**
 *
 * @author Josue Hernández
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        NuevaFacturaBtn = new javax.swing.JButton();
        AnularFacturaBtn = new javax.swing.JButton();
        ActivarFacturaBtn = new javax.swing.JButton();
        NuevoProductoBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Atrasbtn = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NuevaFacturaBtn.setText("Nuevo Factura");
        NuevaFacturaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaFacturaBtnActionPerformed(evt);
            }
        });

        AnularFacturaBtn.setText("Anular Factura");
        AnularFacturaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnularFacturaBtnActionPerformed(evt);
            }
        });

        ActivarFacturaBtn.setText("Activar Factura");
        ActivarFacturaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActivarFacturaBtnActionPerformed(evt);
            }
        });

        NuevoProductoBtn.setText("Nuevo Producto");
        NuevoProductoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoProductoBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Consultar Factura");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reportar Factura");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("By: Josue Hernández");

        Atrasbtn.setText("Atras");
        Atrasbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ActivarFacturaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AnularFacturaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NuevaFacturaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NuevoProductoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(232, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Atrasbtn)
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Atrasbtn)
                .addGap(1, 1, 1)
                .addComponent(NuevoProductoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NuevaFacturaBtn)
                .addGap(15, 15, 15)
                .addComponent(AnularFacturaBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ActivarFacturaBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//metodo de nueva factura
    private void NuevaFacturaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaFacturaBtnActionPerformed
        nuevaFactura.TxtArticulos.setText(pila.toString());
        nuevaFactura.TxtNombre.setText(usuarioActual.getNombre());
        nuevaFactura.TxtCedula.setText(usuarioActual.getCedula() + "");
        nuevaFactura.TxtFac.setText(NumeroFacDisponible + "");
        this.dispose();
        nuevaFactura.setVisible(true);
    }//GEN-LAST:event_NuevaFacturaBtnActionPerformed
//metodo AnularFactura
    private void AnularFacturaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnularFacturaBtnActionPerformed
        int codigo = 0;
        try {
            codigo = Integer.parseInt(JOptionPane.showInputDialog("Inserte un número de código de alguna Factura\n" + listaFacturasActivas.visualizarIDMonto()));
        } catch (HeadlessException | NumberFormatException e) {
        }
        if (codigo != 0 && listaFacturasNulas.estaenLista(codigo + "")) {
            if (listaFacturasNulas.primero == null) {
                listaFacturasNulas.insertarCabezaLista(listaFacturasActivas.buscarLista(codigo + "").getDato());
            } else {
                listaFacturasNulas.insertarLista((NumeroFacDisponible - 1) + "", listaFacturasActivas.buscarLista(codigo + "").getDato());
            }
            listaFacturasActivas.eliminar(codigo + "");
            JOptionPane.showMessageDialog(null, "Se Realizo el tramite con éxito");
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró ninguna factura con ese código");
        }
    }//GEN-LAST:event_AnularFacturaBtnActionPerformed
//metodo de activar Factura
    private void ActivarFacturaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActivarFacturaBtnActionPerformed
        int codigo = 0;
        try {
            codigo = Integer.parseInt(JOptionPane.showInputDialog("Inserte un número de código de alguna Factura\n" + listaFacturasNulas.visualizarIDMonto()));
        } catch (HeadlessException | NumberFormatException e) {
        }
        if (codigo != 0 && listaFacturasNulas.estaenLista(codigo + "")) {
            if (listaFacturasActivas.primero == null) {
                listaFacturasActivas.insertarCabezaLista(listaFacturasNulas.buscarLista(codigo + "").getDato());
            } else {
                listaFacturasActivas.insertarLista((NumeroFacDisponible - 1) + "", listaFacturasNulas.buscarLista(codigo + "").getDato());
            }
            listaFacturasNulas.eliminar(codigo + "");
            JOptionPane.showMessageDialog(null, "Se Realizo el tramite con éxito");
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró ninguna factura con ese código");
        }    }//GEN-LAST:event_ActivarFacturaBtnActionPerformed
//metodo de nuevo producto
    private void NuevoProductoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoProductoBtnActionPerformed
        this.dispose();
        nuevoProducto.setVisible(true);
        TxtProductos.setText(pila.toString());
    }//GEN-LAST:event_NuevoProductoBtnActionPerformed
//metodo de retroceder accion
    private void AtrasbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasbtnActionPerformed
        Utils.usuarioActual = null;
        this.dispose();
        Login.setVisible(true);
    }//GEN-LAST:event_AtrasbtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null, "Facturas: \n" + listaFacturasActivas.visualizarIDMonto() + "\n\n"
                + "Por un monto de: " + listaFacturasActivas.MontoTotal());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int codigo = 0;
        try {
            codigo = Integer.parseInt(JOptionPane.showInputDialog("Inserte un número de código de alguna Factura: \n" + listaFacturasActivas.visualizarIDMonto()));
        } catch (HeadlessException | NumberFormatException e) {
        }
        if (codigo != 0 && listaFacturasActivas.estaenLista(codigo + "")) {
            JOptionPane.showMessageDialog(null, listaFacturasActivas.visualizarFacturaUnica(codigo + "").getDato().toString());
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró ninguna factura con ese código");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActivarFacturaBtn;
    private javax.swing.JButton AnularFacturaBtn;
    private javax.swing.JButton Atrasbtn;
    private javax.swing.JButton NuevaFacturaBtn;
    private javax.swing.JButton NuevoProductoBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
