package Vistas;

import Colas.Cola;
import Colas.ProductosCola;
import Listas.Factura;
import Pilas.Productos;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import proyectoestructuras.Utils;
import static proyectoestructuras.Utils.NumeroFacDisponible;
import static proyectoestructuras.Utils.cola;
import static proyectoestructuras.Utils.listaFacturasActivas;
import static proyectoestructuras.Utils.menu;
import static proyectoestructuras.Utils.pila;
import static proyectoestructuras.Utils.usuarioActual;

/**
 *
 * @author Josue Hernández,  Daniel Guerrero & Cesar Jimenez
 */
public class NuevaFactura extends javax.swing.JFrame {//frame con la clase NuevaFactura

    /**
     * Creates new form NuevaFactura
     */
    public NuevaFactura() {
        initComponents();
        calcular();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtFac = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JLabel();
        TxtCedula = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtArticulos = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtSeleccionados = new javax.swing.JTextArea();
        Atrasbtn = new javax.swing.JButton();
        TxtCodigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtCantidad = new javax.swing.JTextField();
        Agregarbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        TxtSubTotal = new javax.swing.JLabel();
        TxtImpuesto = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtTotal = new javax.swing.JLabel();
        AgregarFac = new javax.swing.JButton();
        Clearbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Número de Factura: ");

        jLabel2.setText("Nombre del Cliente:");

        jLabel3.setText("Cédula: ");

        TxtArticulos.setColumns(20);
        TxtArticulos.setRows(5);
        TxtArticulos.setFocusable(false);
        jScrollPane1.setViewportView(TxtArticulos);

        jLabel4.setText("Digite el código del artículo que desea: ");

        jLabel5.setText("Artículos seleccionados:");

        TxtSeleccionados.setColumns(20);
        TxtSeleccionados.setRows(5);
        TxtSeleccionados.setFocusable(false);
        jScrollPane2.setViewportView(TxtSeleccionados);

        Atrasbtn.setText("Atras");
        Atrasbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasbtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Cantidad:");

        Agregarbtn.setText("Agregar");
        Agregarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarbtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Subtotal:");

        TxtSubTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        TxtImpuesto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel8.setText("Impuesto (13%):");

        jLabel9.setText("Total:");

        TxtTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        AgregarFac.setText("Agregar Factura");
        AgregarFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarFacActionPerformed(evt);
            }
        });

        Clearbtn.setText("Limpiar");
        Clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(49, 49, 49)
                            .addComponent(TxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(AgregarFac)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Clearbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Atrasbtn))
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtFac, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Agregarbtn))
                            .addComponent(jScrollPane1))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Atrasbtn)
                    .addComponent(Clearbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtFac, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(TxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(TxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agregarbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(AgregarFac)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//metodo de retroceder
    private void AtrasbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasbtnActionPerformed
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_AtrasbtnActionPerformed
//metodo de agregar 
    private void AgregarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarbtnActionPerformed
        if (!TxtCodigo.getText().equals("") && !TxtCantidad.getText().equals("")) {
            if (pila.existe(Integer.parseInt(TxtCodigo.getText()))) {
                Productos producto = pila.extrae(Integer.parseInt(TxtCodigo.getText())).getProductos();
                ProductosCola aux = new ProductosCola(producto.getDescripion(),
                        producto.getPrecio(), producto.getCodigo());
                aux.setCantidad(Integer.parseInt(TxtCantidad.getText()));
                cola.encola(aux);
                TxtSeleccionados.setText(cola.toStringConCantidad());
                calcular();
            } else {
                JOptionPane.showMessageDialog(null, "Este código no pertenece a ningún producto");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Digite un ID y una cantidad");
        }
    }//GEN-LAST:event_AgregarbtnActionPerformed
//metodo de limpiar
    private void ClearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearbtnActionPerformed
        TxtCodigo.setText("");
        TxtCantidad.setText("");
        cola = new Cola();
        TxtSeleccionados.setText(cola.toStringConCantidad());
        calcular();
    }//GEN-LAST:event_ClearbtnActionPerformed

    Date fecha = new Date();
    DateFormat Formato = new SimpleDateFormat("yyyy/mm/dd");
    DateFormat Formato2 = new SimpleDateFormat("HH:mm:ss");
    //Metodo de agregar a la factura 
    private void AgregarFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarFacActionPerformed
        if (cola.CantidadArticulos() != 0) {
            if (listaFacturasActivas.primero == null) {
                listaFacturasActivas.insertarCabezaLista(new Factura(NumeroFacDisponible++ + "",
                        usuarioActual.getNombre(),
                        usuarioActual.getCedula(),
                        Formato.format(fecha),
                        Formato2.format(fecha),
                        cola,
                        cola.CantidadArticulos(),
                        subtotal,
                        ((int) impuesto),
                        total,
                        true));
            } else {
                listaFacturasActivas.insertarLista((NumeroFacDisponible - 1) + "", new Factura(NumeroFacDisponible++ + "",
                        usuarioActual.getNombre(),
                        usuarioActual.getCedula(),
                        Formato.format(fecha),
                        Formato2.format(fecha),
                        cola,
                        cola.CantidadArticulos(),
                        subtotal,
                        ((int) impuesto),
                        total,
                        true));
            }
            JOptionPane.showMessageDialog(null, "Se realizo la factura con exito");
            TxtCodigo.setText("");
            TxtCantidad.setText("");
            cola = new Cola();
            TxtSeleccionados.setText(cola.toStringConCantidad());
            calcular();
            this.dispose();
            menu.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No se ha insertado ningún producto");
        }
    }//GEN-LAST:event_AgregarFacActionPerformed

    private int subtotal = 0;
    private double impuesto = 0;
    private int total = 0;
//metodo de calular los precios con los impuestos
    public void calcular() {
        subtotal = cola.muestraPrecio();
        impuesto = subtotal * 0.13;
        total = subtotal + ((int) impuesto);
        TxtSubTotal.setText(subtotal + "");
        TxtImpuesto.setText(impuesto + "");
        TxtTotal.setText(total + "");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarFac;
    private javax.swing.JButton Agregarbtn;
    private javax.swing.JButton Atrasbtn;
    private javax.swing.JButton Clearbtn;
    public static javax.swing.JTextArea TxtArticulos;
    private javax.swing.JTextField TxtCantidad;
    public static javax.swing.JLabel TxtCedula;
    private javax.swing.JTextField TxtCodigo;
    public static javax.swing.JLabel TxtFac;
    private javax.swing.JLabel TxtImpuesto;
    public static javax.swing.JLabel TxtNombre;
    private javax.swing.JTextArea TxtSeleccionados;
    private javax.swing.JLabel TxtSubTotal;
    private javax.swing.JLabel TxtTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
